// ============================================================
// El laboratorio de pronóstico macro de LATAM — /labs/macro-forecast
//
// Bloque propio y no una clave más de projects.ts: la página trae el texto de seis
// piezas interactivas, y meterlo en el fichero de las cinco piezas de trabajo lo
// habría duplicado en tamaño. La forma de `es` y `en` es la misma, incluidas las
// longitudes de los arrays: `npm run check:dict` lo prueba.
//
// Las cifras salen de macro-forecast-lab-latam v1.1.0 (salidas/ y RESULTADOS*.md).
// Se dice «economías» y no «países» a propósito: `check:figures` reserva «N países»
// para el alcance profesional del CV, y un 20 aquí no es esa afirmación.
// ============================================================

import type { Metric } from "./types";

export const MACRO_REPO = "https://github.com/DavinsonR/macro-forecast-lab-latam";

export const forecast = {
  es: {
    forecastLab: {
      metaTitle: "Pronóstico macro en LATAM",
      metaDesc:
        "Pronósticos 2026–2027 del crecimiento de 20 economías de América Latina, con bandas al 95 % y su acierto medido. Un laboratorio abierto.",
      kicker: "Lab · macro-forecast-lab-latam",
      pill: "LABORATORIO ABIERTO",
      title: "Pronostico el crecimiento de 20 economías de América Latina, y demuestro cuánto vale cada pronóstico.",
      subtitle:
        "Pronósticos 2026–2027 por economía, con bandas de confianza al 80 y al 95 % y su tasa de acierto medida en el backtest, año por año. Detrás, un laboratorio que puso a competir trece modelos —del AR(1) al LSTM— contra el pronóstico ingenuo, con cada ganancia sometida a su prueba. Fíltralo, compáralo y juega contra él.",
      meta: "Python · statsmodels · scikit-learn · PyTorch · origen móvil · Diebold-Mariano, Holm y Wilcoxon",
      timeline: "v1.1.0 · septiembre de 2026 · código y resultados públicos",
      figures: [
        { value: "20", label: "economías bajo el mismo protocolo", note: "19 con serie anual desde 1961 y ocho trimestrales", href: "#region" },
        { value: "0,86", label: "error del AR(1) frente al ingenuo, en calma", note: "mediana de 19 economías anuales · Wilcoxon p < 0,001", href: "#region" },
        { value: "0 de 27", label: "mejores modelos por economía que sobreviven a Holm", note: "en las 27 series de LATAM, trimestrales y anuales", href: "#holm" },
        { value: "17 de 20", label: "economías sin un solo año con las 33 variables", note: "la frontera se mide antes de modelar", href: "#veredicto" },
      ] as Metric[],
      nav: [
        { id: "panorama", label: "Panorama" },
        { id: "juega", label: "Juega" },
        { id: "backtest", label: "Origen móvil" },
        { id: "region", label: "La región" },
        { id: "frecuencia", label: "Frecuencia" },
        { id: "holm", label: "Holm" },
        { id: "veredicto", label: "Veredicto" },
        { id: "reproducir", label: "Reproducir" },
      ],
      dashboard: {
        label: "Panorama",
        title: "Veinte economías, sesenta y cinco años y su pronóstico, en un solo tablero",
        body: "Elige economías, una métrica y un período: todos los gráficos se mueven con el filtro, y sin filtro ves la región entera. Los marcadores señalan los choques detrás de las caídas —el corralito, el Tequila, las hiperinflaciones— y la zona sombreada a la derecha es el pronóstico 2026–2027 con sus bandas.",
      },
      play: {
        label: "Tú contra el ingenuo",
        title: "Antes de leer el resultado, intenta ganarle tú",
        body: "Te enseño una economía hasta un año cualquiera. Arrastra el punto ámbar hasta donde crees que irá el crecimiento del período siguiente y revela. El ingenuo solo repite el último dato. Juega unas rondas, y prueba la de 2020.",
      },
      backtest: {
        label: "Origen móvil",
        title: "Cómo se evalúa sin hacer trampa: origen por origen",
        body: "Cada modelo se reentrena con lo que había hasta el origen, pronostica un paso, anota su error y avanza. Nunca ve el dato que pronostica. Mueve el origen o dale a reproducir, y mira cómo el orden entre modelos cambia de golpe cuando entra 2020.",
      },
      region: {
        label: "La región",
        title: "La región entera, un veredicto que sí aguanta",
        body: "Cada punto es una economía: su error dividido por el del ingenuo. A la izquierda de la línea, el modelo gana. La prueba que importa no es la de cada economía, sino si todas empujan hacia el mismo lado: esa es la columna de Wilcoxon.",
      },
      frequency: {
        label: "Frecuencia",
        title: "El mismo LSTM gana o pierde según la frecuencia. No es la red",
        body: "En la ruptura de Colombia el LSTM perdía contra el ingenuo con datos mensuales y ganaba con trimestrales. Un experimento con predicciones registradas antes de correr separó frecuencia, ajuste y fuente. Cambia la frecuencia y mira qué barra se mueve.",
      },
      holm: {
        label: "Comparaciones múltiples",
        title: "Prueba 18 modelos al 5 % y alguno ganará por azar",
        body: "La calma del ISE mensual de Colombia es donde más modelos parecen ganarle al ingenuo. Activa la corrección de Holm, que exige más a quien se prueba junto a muchos otros, y cuenta cuántas estrellas sobreviven.",
      },
      verdict: {
        label: "Veredicto",
        title: "Lo que queda en pie, y lo que no",
        headline: "En calma, un AR(1) de un parámetro le gana al ingenuo en toda la región. Nada más resiste en toda la región.",
        stat: "0,861 · p < 0,001 · 19 economías",
        body: "Es la mediana del error del AR(1) dividido por el del ingenuo en las 19 economías anuales, y todas empujan hacia el mismo lado. En las ocho trimestrales pasa lo mismo en las ocho. Dentro de cada economía, el mejor modelo no sobrevive a la corrección por comparaciones múltiples en ninguna de las 27 series. La excepción es la calma mensual de Colombia, con 246 meses: ahí cuatro modelos sí la resisten.",
        holds: {
          label: "Queda establecido",
          items: [
            "En calma, el AR(1) le gana al ingenuo en toda la región: 8 de 8 economías trimestrales y una mediana de 0,861 en las 19 anuales.",
            "La frontera de cobertura es regional: en 17 de 20 economías no hay un solo año con las 33 variables.",
            "La combinación por régimen que funcionaba en el ISE de Colombia no se replica fuera de él.",
            "La aparente inversión de Colombia entre frecuencias la produce la referencia: el ingenuo es mucho más difícil de batir a un mes vista que a un trimestre.",
          ],
        },
        not: {
          label: "No queda establecido",
          items: [
            "Un ranking de modelos dentro de una economía de LATAM: tras Holm, ningún mejor modelo queda en pie en las 27 series.",
            "Nada sobre la habilidad de los modelos en la ruptura anual: dos observaciones por economía y un ingenuo que pierde por construcción.",
            "Que las redes sirvan o no en la ruptura trimestral: ganan en 5 de 8 economías y ninguna victoria es significativa.",
          ],
        },
      },
      method: {
        label: "Protocolo",
        title: "Las reglas que hacen que un número valga",
        items: [
          { title: "Nada ve el futuro", body: "Origen móvil con ventana expansiva: cada modelo se reentrena en cada origen con lo que había hasta ahí. Los escaladores se ajustan con el tramo de entrenamiento y las redes paran temprano contra una validación recortada del propio entrenamiento." },
          { title: "Ninguna frecuencia se rellena", body: "Si una variable es anual, se queda anual. Y una serie no salta años: se usa el tramo contiguo más largo, porque un modelo de rezagos trataría 1985 → 1987 como un solo año." },
          { title: "Un fallo no es una victoria", body: "Un modelo que no pronostica en más del 10 % de los orígenes queda fuera del ranking. Una vez, uno pareció ganar porque solo había competido en los orígenes fáciles." },
          { title: "Ninguna ganancia sin su prueba", body: "Diebold-Mariano contra el ingenuo, con la p ajustada por Holm. Entre economías, Wilcoxon. Una diferencia de error sin p no distingue una mejora del ruido." },
          { title: "El régimen se asigna por lo que se pronostica", body: "La calma y la ruptura se definen por el período pronosticado, no por el origen. La versión 0.1.0 lo hacía al revés y la caída de 2020 quedaba en la calma: lo encontró la auditoría." },
          { title: "Lo que se eligió mirando, es hipótesis", body: "La ruptura 2020–2021 se eligió después de ver los datos. Todo lo que dependa de ella se publica como hipótesis. Las predicciones del experimento de frecuencia se escribieron antes de correrlo." },
        ],
      },
      reproduce: {
        label: "Reproducir",
        title: "Todo corre sin red, desde el repositorio",
        steps: [
          { cmd: "uv sync", body: "El entorno exacto desde uv.lock, torch incluido." },
          { cmd: "uv run python -m macro_lab.lab_latam", body: "Las pistas C y D: 8 economías trimestrales y 20 anuales." },
          { cmd: "uv run python -m macro_lab.lab_frecuencia", body: "El experimento de frecuencia, ajuste y fuente, con su regla pre-registrada." },
          { cmd: "uv run python -m macro_lab.exportar_web", body: "Los JSON que lee esta página. Nada se recalcula aquí: se lee." },
        ],
        note: "Los datos del Banco Mundial y del FMI van versionados en el repositorio. Las series trimestrales del FMI están ajustadas estacionalmente, porque el IFS no publica la versión sin ajustar para esas economías, y eso se declara. Los errores encontrados y su causa están en la bitácora del repositorio.",
      },
      status: {
        label: "Estado",
        title: "Un experimento cerrado, publicado con lo que no funcionó",
        items: [
          "v1.1.0 publicada: cuatro pistas, un experimento de frecuencia con pre-registro y 17 pruebas del protocolo en CI.",
          "La auditoría de la v1.0.0 corrigió ocho errores, y dos titulares de la versión anterior no sobrevivieron. Está todo en la bitácora.",
          "Fuera de alcance, y dicho: horizontes de más de un paso, una combinación 50/50 fija y datos en tiempo real para las variables anuales.",
        ],
      },
      repoCta: "Ver el código y la bitácora",
      resultsCta: "Leer los resultados completos",
      backCta: "Volver al inicio",
      lab: {
        loading: "Cargando las series del laboratorio…",
        error: "No se pudieron cargar los datos del laboratorio.",
        retry: "Reintentar",
        freq: "Frecuencia",
        anual: "Anual",
        trimestral: "Trimestral",
        economy: "Economía",
        regime: "Régimen",
        calma: "Calma",
        ruptura: "Ruptura 2020–2021",
        naive: "Ingenuo",
        you: "Tú",
        actual: "Real",
        growth: "Crecimiento del PIB real, % anual",
        yearAxis: "Año",
        models: {
          naive: "Ingenuo",
          ar1: "AR(1)",
          arima: "ARIMA(1,1,1)",
          rf: "Random Forest",
          lstm: "LSTM",
          comb: "Combinación RF/AR(1)",
        },
        dash: {
          economies: "Economías",
          economiesBtn: "{n} economías",
          allEconomies: "Todas ({n})",
          clearAll: "Mostrar todas",
          median: "Mediana de la región",
          none: "Ninguna economía",
          search: "Buscar economía",
          clear: "Limpiar",
          all: "Todos",
          presetsLabel: "Atajo",
          custom: "Selección propia",
          presets: {
            big: "Las seis grandes",
            andes: "Andinos",
            south: "Cono Sur",
            central: "Centroamérica",
            caribbean: "Caribe y México",
          },
          indicator: "Métrica",
          period: "Período",
          from: "Desde",
          to: "Hasta",
          eventTypes: "Tipos de evento",
          eventTypesBtn: "{n} de {total} tipos",
          goTo: "Ir a un evento",
          goToPlaceholder: "Elegir un evento…",
          close: "Cerrar",
          kpis: {
            mean: "Promedio del período",
            vol: "Volatilidad típica",
            volNote: "desviación estándar media por economía",
            worst: "Peor registro",
            best: "Mejor registro",
            falls: "Años con el PIB en caída",
            fallsNote: "{n} de {total} años-economía del período",
            coverage: "{n} datos en el período",
          },
          chart: {
            title: "La serie, economía por economía",
            hint: "Toca un marcador numerado o una línea punteada para leer el evento. Con el crecimiento del PIB, la zona sombreada a la derecha es el pronóstico con su banda del 80 % (la del 95 % está en el recuadro de abajo).",
          },
          table: {
            title: "Economías en el período ({n})",
            hint: "Ordena por cualquier columna; toca una fila para añadirla o quitarla del filtro.",
            economy: "Economía",
            mean: "Promedio",
            vol: "Volatilidad",
            min: "Mínimo",
            max: "Máximo",
            last: "Último",
          },
          forecast: {
            toggle: "Pronóstico 2026–2027",
            zone: "Pronóstico",
            title: "Pronóstico {from}–{to}: crecimiento del PIB real con bandas al 80 y 95 %",
            hint: "AR(1), el modelo que le gana al ingenuo en toda la región. En el backtest, la banda del 95 % contuvo el dato real el {c95} de las veces y la del 80 %, el {c80} ({n} pronósticos a un año).",
            economy: "Economía",
            last: "Último dato",
            to: "a",
            coverage: "Acierto banda 95 %",
            coverageNote: "{name}: en el backtest, su banda del 95 % contuvo el dato real en el {pct} de {n} años.",
            lowCoverage: "Menos de lo prometido: léala como más estrecha de lo que es.",
            disclaimer: "Pronóstico estadístico: extrapola la historia de cada economía con un AR(1) ajustado hasta el último dato del Banco Mundial. No incorpora información posterior ni juicio experto, y las bandas son anchas porque la región vivió crisis que el modelo sabe que pueden repetirse.",
            axisY: "Crecimiento del PIB real (% anual)",
            fanLabel: "Historia y pronóstico",
            history: "Historia",
            mean: "Pronóstico medio",
            band80: "Banda 80 %",
            band95: "Banda 95 %",
          },
          scatter: {
            title: "Nivel frente a volatilidad",
            x: "Volatilidad (desviación estándar)",
            y: "Promedio del período",
            hint: "Cada punto es una economía en el período elegido. Toca uno para añadirla o quitarla.",
          },
          heat: {
            title: "Mapa de calor: economía por año",
            hint: "Cada celda es un año de una economía. Toca un nombre para añadirla o quitarla.",
            noData: "sin dato",
            eventDot: "evento",
          },
          timeline: {
            title: "Cronología de choques y reformas",
            empty: "Ningún evento de las economías elegidas en este período.",
            focus: "Enfocar este período",
            regional: "Toda la región",
            note: "Cronología editorial con fechas públicas. Las magnitudes las pone la serie, no el texto.",
          },
          season: {
            title: "Estacionalidad: Colombia mes a mes",
            series: "Serie del ISE",
            years: "Años a comparar",
            viewYears: "Por año",
            viewProfile: "Perfil promedio",
            level: "Índice del ISE (nivel)",
            profile: "Perfil estacional promedio",
            profileNote: "Desvío de cada mes frente al promedio de su año, en todos los años completos.",
            why: "Solo Colombia: el ISE del DANE es la única serie mensual sin ajustar del laboratorio. Las trimestrales del FMI vienen desestacionalizadas y ya no tienen estacionalidad que mostrar.",
            months: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
          },
          missing: "Cobertura incompleta en el Banco Mundial para esta métrica: {names}.",
          yearsOf: "{n} de {total} años",
          year: "Año",
          source: "Fuente: Banco Mundial, World Development Indicators (CC BY 4.0). Pronóstico: AR(1) de macro-forecast-lab-latam.",
          filters: "Filtros",
        },
        play: {
          handle: "Tu pronóstico para {period}",
          instructions: "Arrastra el punto ámbar, o enfócalo y usa las flechas (↑↓ una décima, RePág/AvPág un punto).",
          yourCall: "Tu pronóstico para {period}",
          reveal: "Revelar",
          next: "Otra ronda",
          crash: "Probar 2020",
          errorsTitle: "Error de cada uno en {period}",
          score: "Tu marcador",
          rounds: "rondas jugadas",
          beatNaive: "Le ganaste al ingenuo en {won} de {n}",
          yourMae: "Tu error medio",
          reset: "Empezar de cero",
          hint: "Pista: el AR(1) casi nunca se aleja del promedio. El ingenuo nunca se aleja del último dato.",
        },
        backtest: {
          origin: "Origen",
          play: "Reproducir",
          pause: "Pausa",
          trained: "Entrenado con {n} períodos hasta {origin}",
          forecastFor: "Pronóstico para {period}",
          running: "Error acumulado frente al ingenuo (1 = igual)",
          toggle: "Modelos visibles",
          window: "tramo de entrenamiento",
          axisRel: "Error ÷ error del ingenuo",
          axisOrigin: "Origen del pronóstico",
          errorAt: "error en {period}",
        },
        region: {
          axis: "Error del modelo ÷ error del ingenuo (escala log)",
          better: "gana al ingenuo",
          worse: "pierde",
          median: "Mediana",
          wilcoxon: "Wilcoxon p",
          sig: "DM: economías con una mejora de Diebold-Mariano p < 0,05, sin ajustar.",
          of: "de",
          select: "Toca un punto para llevar esa economía al juego y al origen móvil.",
          selected: "Economía seleccionada: {name}",
          table: "Ver los valores en una tabla",
          excluded: "fuera por cobertura",
          quarterlyNote: "Las series trimestrales del FMI vienen ajustadas estacionalmente; se declara porque ese ajuste ya vio el futuro.",
        },
        frequency: {
          monthly: "Mensual (ISE)",
          quarterly: "Trimestral (ISE)",
          maeTitle: "Error medio en la ruptura, puntos porcentuales",
          gain: "LSTM frente al ingenuo",
          arms: "Los cuatro brazos del experimento",
          arm: "Serie",
          armNames: {
            M: "ISE mensual, sin ajuste",
            A: "ISE trimestral, sin ajuste",
            B: "ISE trimestral, ajustado",
            C: "PIB del FMI, ajustado",
          },
          reading: "El LSTM se equivoca parecido en las dos frecuencias. El que cambia es el ingenuo: a un mes vista es muy difícil de batir, y a un trimestre vista no.",
        },
        holm: {
          switch: "Corregir por 18 comparaciones (Holm)",
          model: "Modelo",
          gain: "vs ingenuo",
          p: "p",
          pHolm: "p Holm",
          count: "{n} de 18 mejoras significativas al 5 %",
          note: "ISE mensual de Colombia, calma (102 orígenes). Diebold-Mariano pareado contra el ingenuo.",
        },
      },
    },
  },
  en: {
    forecastLab: {
      metaTitle: "Macro forecasting across LATAM",
      metaDesc:
        "2026–2027 growth forecasts for 20 Latin American economies, with 95 % bands and their measured hit rate. An open lab.",
      kicker: "Lab · macro-forecast-lab-latam",
      pill: "OPEN LAB",
      title: "I forecast growth for 20 Latin American economies, and prove what every forecast is worth.",
      subtitle:
        "2026–2027 forecasts for every economy, with 80 and 95 % confidence bands and their hit rate measured in the backtest, year by year. Behind them, a lab that pitted thirteen models —from an AR(1) to an LSTM— against the naive forecast, with every gain put to its test. Filter it, compare it and play against it.",
      meta: "Python · statsmodels · scikit-learn · PyTorch · rolling origin · Diebold-Mariano, Holm and Wilcoxon",
      timeline: "v1.1.0 · September 2026 · code and results public",
      figures: [
        { value: "20", label: "economies under one protocol", note: "19 with annual series since 1961, and eight quarterly", href: "#region" },
        { value: "0.86", label: "AR(1) error relative to naive, in calm", note: "median of 19 annual economies · Wilcoxon p < 0.001", href: "#region" },
        { value: "0 of 27", label: "per-economy best models that survive Holm", note: "across the 27 LATAM series, quarterly and annual", href: "#holm" },
        { value: "17 of 20", label: "economies without a single year holding all 33 variables", note: "the frontier is measured before modelling", href: "#veredicto" },
      ] as Metric[],
      nav: [
        { id: "panorama", label: "Overview" },
        { id: "juega", label: "Play" },
        { id: "backtest", label: "Rolling origin" },
        { id: "region", label: "The region" },
        { id: "frecuencia", label: "Frequency" },
        { id: "holm", label: "Holm" },
        { id: "veredicto", label: "Verdict" },
        { id: "reproducir", label: "Reproduce" },
      ],
      dashboard: {
        label: "Overview",
        title: "Twenty economies, sixty-five years and their forecast, on one dashboard",
        body: "Pick economies, a metric and a period: every chart moves with the filter, and with no filter you see the whole region. The markers flag the shocks behind the falls —the corralito, the Tequila crisis, the hyperinflations— and the shaded zone on the right is the 2026–2027 forecast with its bands.",
      },
      play: {
        label: "You against naive",
        title: "Before you read the result, try to beat it yourself",
        body: "I show you an economy up to some year. Drag the amber dot to where you think next period's growth will land, then reveal. Naive just repeats the last value. Play a few rounds, and try 2020.",
      },
      backtest: {
        label: "Rolling origin",
        title: "How to evaluate without cheating: one origin at a time",
        body: "Each model is retrained on what existed up to the origin, forecasts one step, logs its error and moves on. It never sees the value it forecasts. Move the origin or press play, and watch the order between models flip the moment 2020 comes in.",
      },
      region: {
        label: "The region",
        title: "The whole region, one verdict that holds",
        body: "Each dot is an economy: its error divided by naive's. Left of the line, the model wins. The test that matters is not each economy's, but whether they all push the same way: that is the Wilcoxon column.",
      },
      frequency: {
        label: "Frequency",
        title: "The same LSTM wins or loses with the frequency. It is not the network",
        body: "In Colombia's break the LSTM lost to naive on monthly data and won on quarterly data. An experiment with predictions registered before running it separated frequency, adjustment and source. Switch the frequency and watch which bar moves.",
      },
      holm: {
        label: "Multiple comparisons",
        title: "Test 18 models at 5 % and one will win by chance",
        body: "Calm periods in Colombia's monthly ISE are where the most models seem to beat naive. Turn on Holm's correction, which asks more of anyone tested alongside many others, and count how many stars survive.",
      },
      verdict: {
        label: "Verdict",
        title: "What stands, and what does not",
        headline: "In calm times, a one-parameter AR(1) beats naive across the region. Nothing else holds region-wide.",
        stat: "0.861 · p < 0.001 · 19 economies",
        body: "That is the median of the AR(1) error divided by naive's across the 19 annual economies, and they all push the same way. The eight quarterly economies show the same thing, all eight of them. Within each economy, the best model fails the correction for multiple comparisons in all 27 series. The exception is Colombia's monthly calm, with 246 months: there four models do withstand it.",
        holds: {
          label: "Established",
          items: [
            "In calm times, the AR(1) beats naive across the region: 8 of 8 quarterly economies and a median of 0.861 across the 19 annual ones.",
            "The coverage frontier is regional: in 17 of 20 economies there is not one year holding all 33 variables.",
            "The regime combination that worked on Colombia's ISE does not replicate outside it.",
            "Colombia's apparent reversal across frequencies comes from the benchmark: naive is far harder to beat one month ahead than one quarter ahead.",
          ],
        },
        not: {
          label: "Not established",
          items: [
            "A ranking of models within any LATAM economy: after Holm, no best model is left standing in the 27 series.",
            "Anything about skill in the annual break: two observations per economy and a naive that loses by construction.",
            "Whether networks help in the quarterly break: they win in 5 of 8 economies and no win is significant.",
          ],
        },
      },
      method: {
        label: "Protocol",
        title: "The rules that make a number count",
        items: [
          { title: "Nothing sees the future", body: "Rolling origin with an expanding window: every model is retrained at every origin on what existed up to it. Scalers fit on the training span only, and networks stop early against a validation cut from their own training data." },
          { title: "No frequency is filled in", body: "An annual variable stays annual. And a series never skips years: the longest contiguous span is used, because a lag model would treat 1985 → 1987 as a single year." },
          { title: "A failure is not a win", body: "A model that fails to forecast at more than 10 % of the origins is dropped from the ranking. Once, a model looked like the winner because it had only competed on the easy origins." },
          { title: "No gain without its test", body: "Diebold-Mariano against naive, with the p adjusted by Holm. Across economies, Wilcoxon. An error difference without a p cannot tell an improvement from noise." },
          { title: "The regime follows what is forecast", body: "Calm and break are defined by the forecast period, not the origin. Version 0.1.0 had it backwards and the 2020 crash landed in the calm: the audit caught it." },
          { title: "What was chosen by looking is a hypothesis", body: "The 2020–2021 break was chosen after seeing the data, so everything that depends on it is published as a hypothesis. The frequency experiment's predictions were written down before it ran." },
        ],
      },
      reproduce: {
        label: "Reproduce",
        title: "Everything runs offline, from the repository",
        steps: [
          { cmd: "uv sync", body: "The exact environment from uv.lock, torch included." },
          { cmd: "uv run python -m macro_lab.lab_latam", body: "Tracks C and D: 8 quarterly and 20 annual economies." },
          { cmd: "uv run python -m macro_lab.lab_frecuencia", body: "The frequency, adjustment and source experiment, with its pre-registered rule." },
          { cmd: "uv run python -m macro_lab.exportar_web", body: "The JSON this page reads. Nothing is recomputed here: it is read." },
        ],
        note: "World Bank and IMF data are versioned in the repository. The IMF quarterly series are seasonally adjusted, because the IFS does not publish the unadjusted version for those economies, and that is stated. The errors found and their causes are in the repository's log.",
      },
      status: {
        label: "Status",
        title: "A closed experiment, published with what did not work",
        items: [
          "v1.1.0 released: four tracks, a pre-registered frequency experiment and 17 protocol tests in CI.",
          "The v1.0.0 audit fixed eight errors, and two headlines from the previous version did not survive. It is all in the log.",
          "Out of scope, and said so: horizons beyond one step, a fixed 50/50 combination, and real-time vintages for the annual variables.",
        ],
      },
      repoCta: "See the code and the log",
      resultsCta: "Read the full results",
      backCta: "Back to home",
      lab: {
        loading: "Loading the lab's series…",
        error: "The lab's data could not be loaded.",
        retry: "Retry",
        freq: "Frequency",
        anual: "Annual",
        trimestral: "Quarterly",
        economy: "Economy",
        regime: "Regime",
        calma: "Calm",
        ruptura: "Break 2020–2021",
        naive: "Naive",
        you: "You",
        actual: "Actual",
        growth: "Real GDP growth, % year on year",
        yearAxis: "Year",
        models: {
          naive: "Naive",
          ar1: "AR(1)",
          arima: "ARIMA(1,1,1)",
          rf: "Random Forest",
          lstm: "LSTM",
          comb: "RF/AR(1) combination",
        },
        dash: {
          economies: "Economies",
          economiesBtn: "{n} economies",
          allEconomies: "All ({n})",
          clearAll: "Show all",
          median: "Regional median",
          none: "No economy",
          search: "Search an economy",
          clear: "Clear",
          all: "All",
          presetsLabel: "Shortcut",
          custom: "Custom selection",
          presets: {
            big: "The big six",
            andes: "Andean",
            south: "Southern Cone",
            central: "Central America",
            caribbean: "Caribbean and Mexico",
          },
          indicator: "Metric",
          period: "Period",
          from: "From",
          to: "To",
          eventTypes: "Event types",
          eventTypesBtn: "{n} of {total} types",
          goTo: "Go to an event",
          goToPlaceholder: "Pick an event…",
          close: "Close",
          kpis: {
            mean: "Period average",
            vol: "Typical volatility",
            volNote: "mean standard deviation per economy",
            worst: "Worst reading",
            best: "Best reading",
            falls: "Years with GDP falling",
            fallsNote: "{n} of {total} economy-years in the period",
            coverage: "{n} data points in the period",
          },
          chart: {
            title: "The series, economy by economy",
            hint: "Tap a numbered marker or a dotted line to read the event. With GDP growth, the shaded zone on the right is the forecast with its 80 % band (the 95 % band is in the panel below).",
          },
          table: {
            title: "Economies in the period ({n})",
            hint: "Sort by any column; tap a row to add or remove it.",
            economy: "Economy",
            mean: "Average",
            vol: "Volatility",
            min: "Min",
            max: "Max",
            last: "Latest",
          },
          forecast: {
            toggle: "2026–2027 forecast",
            zone: "Forecast",
            title: "{from}–{to} forecast: real GDP growth with 80 and 95 % bands",
            hint: "AR(1), the model that beats naive across the region. In the backtest, the 95 % band held the actual value {c95} of the time and the 80 % band {c80} ({n} one-year forecasts).",
            economy: "Economy",
            last: "Latest",
            to: "to",
            coverage: "95 % band hit rate",
            coverageNote: "{name}: in the backtest, its 95 % band held the actual value in {pct} of {n} years.",
            lowCoverage: "Below what it promises: read it as narrower than it is.",
            disclaimer: "A statistical forecast: it extrapolates each economy's history with an AR(1) fitted up to the latest World Bank figure. It adds no later information and no expert judgment, and the bands are wide because the region has lived through crises the model knows can happen again.",
            axisY: "Real GDP growth (% a year)",
            fanLabel: "History and forecast",
            history: "History",
            mean: "Mean forecast",
            band80: "80 % band",
            band95: "95 % band",
          },
          scatter: {
            title: "Level against volatility",
            x: "Volatility (standard deviation)",
            y: "Period average",
            hint: "Each dot is an economy over the chosen period. Tap one to add or remove it.",
          },
          heat: {
            title: "Heat map: economy by year",
            hint: "Each cell is one year of one economy. Tap a name to add or remove it.",
            noData: "no data",
            eventDot: "event",
          },
          timeline: {
            title: "A timeline of shocks and reforms",
            empty: "No events for the chosen economies in this period.",
            focus: "Focus this period",
            regional: "Whole region",
            note: "An editorial timeline with public dates. The series carries the magnitudes, not the text.",
          },
          season: {
            title: "Seasonality: Colombia month by month",
            series: "ISE series",
            years: "Years to compare",
            viewYears: "By year",
            viewProfile: "Average profile",
            level: "ISE index (level)",
            profile: "Average seasonal profile",
            profileNote: "Each month's deviation from its year's average, across all complete years.",
            why: "Colombia only: DANE's ISE is the lab's only unadjusted monthly series. The IMF quarterly series come seasonally adjusted and have no seasonality left to show.",
            months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
          },
          missing: "Incomplete World Bank coverage for this metric: {names}.",
          yearsOf: "{n} of {total} years",
          year: "Year",
          source: "Source: World Bank, World Development Indicators (CC BY 4.0). Forecast: AR(1) from macro-forecast-lab-latam.",
          filters: "Filters",
        },
        play: {
          handle: "Your forecast for {period}",
          instructions: "Drag the amber dot, or focus it and use the arrows (↑↓ a tenth, PgUp/PgDn a full point).",
          yourCall: "Your forecast for {period}",
          reveal: "Reveal",
          next: "Another round",
          crash: "Try 2020",
          errorsTitle: "Everyone's error in {period}",
          score: "Your score",
          rounds: "rounds played",
          beatNaive: "You beat naive in {won} of {n}",
          yourMae: "Your mean error",
          reset: "Start over",
          hint: "Hint: the AR(1) rarely strays from the average. Naive never strays from the last value.",
        },
        backtest: {
          origin: "Origin",
          play: "Play",
          pause: "Pause",
          trained: "Trained on {n} periods up to {origin}",
          forecastFor: "Forecast for {period}",
          running: "Cumulative error relative to naive (1 = equal)",
          toggle: "Visible models",
          window: "training span",
          axisRel: "Error ÷ naive's error",
          axisOrigin: "Forecast origin",
          errorAt: "error in {period}",
        },
        region: {
          axis: "Model error ÷ naive error (log scale)",
          better: "beats naive",
          worse: "loses",
          median: "Median",
          wilcoxon: "Wilcoxon p",
          sig: "DM: economies with a Diebold-Mariano improvement at p < 0.05, unadjusted.",
          of: "of",
          select: "Tap a dot to send that economy to the game and to the rolling origin.",
          selected: "Selected economy: {name}",
          table: "See the values in a table",
          excluded: "dropped for coverage",
          quarterlyNote: "The IMF quarterly series come seasonally adjusted; it is stated because that adjustment has already seen the future.",
        },
        frequency: {
          monthly: "Monthly (ISE)",
          quarterly: "Quarterly (ISE)",
          maeTitle: "Mean error in the break, percentage points",
          gain: "LSTM against naive",
          arms: "The experiment's four arms",
          arm: "Series",
          armNames: {
            M: "Monthly ISE, unadjusted",
            A: "Quarterly ISE, unadjusted",
            B: "Quarterly ISE, adjusted",
            C: "IMF GDP, adjusted",
          },
          reading: "The LSTM errs about as much at both frequencies. What changes is naive: one month ahead it is very hard to beat, and one quarter ahead it is not.",
        },
        holm: {
          switch: "Correct for 18 comparisons (Holm)",
          model: "Model",
          gain: "vs naive",
          p: "p",
          pHolm: "Holm p",
          count: "{n} of 18 improvements significant at 5 %",
          note: "Colombia's monthly ISE, calm periods (102 origins). Paired Diebold-Mariano against naive.",
        },
      },
    },
  },
};

export type ForecastCopy = (typeof forecast)["es"]["forecastLab"];
export type LabCopy = ForecastCopy["lab"];
